# Cloudflare Pages Configuration for Thoughtmarks Landing
# Static site deployment configuration

name = "thoughtmarks-landing"
pages_build_output_dir = "dist"
compatibility_date = "2025-10-24"

# Build configuration
[build]
command = "npm install && npm run build:site"

# Production deployment settings
[env.production]
vars = { ENVIRONMENT = "production" }

# Preview deployment settings  
[env.preview]
vars = { ENVIRONMENT = "preview" }

